scriptencoding utf-8
syntax on

set autoindent
set background=dark
set backspace=indent,eol,start
set belloff=all
set expandtab
set hlsearch
set number
set omnifunc=syntaxcomplete#Complete
set shiftwidth=3
set shortmess-=S
set splitbelow
set splitright
set tabstop=4
set ttimeoutlen=100
set visualbell
" Set character code emitted for visualbell to null
set t_vb=
" searches are case insensitive unless upper case char in search text
" for some reason, need to set ignorecase before smartcase for it to work
set ignorecase
set smartcase
set cursorline

let g:default_code_text_width = 78
let g:python_highlight_all = 1
let g:termdebug_popup = 0
let g:termdebug_wide = 163

filetype plugin on

if &shell =~# 'fish$'
    set shell=bash
endif
if &term =~ '^xterm' || &term =~'^screen'
    " Normal Mode: solid block
    let &t_EI .= "\<Esc>[2 q"
    " Replace Mode: blinking block
    let &t_SR .= "\<Esc>[1 q"
    " Insert Mode: blinking vertical bar
    let &t_SI .= "\<Esc>[5 q"
endif

function SetIndentation(size, expand_tab = v:true)
    let &l:tabstop=a:size
    let &l:shiftwidth=a:size
    " let &l:expandtab=!a:expand_tab
    let &l:expandtab=a:expand_tab
endfunction

autocmd Filetype cs :call SetIndentation(3)
autocmd Filetype cpp :call SetIndentation(3)
autocmd Filetype h :call SetIndentation(3)
autocmd Filetype html :call SetIndentation(2)
autocmd Filetype fish :call SetIndentation(4)
autocmd Filetype py :call SetIndentation(4)
autocmd Filetype python :call SetIndentation(4)
autocmd Filetype json :call SetIndentation(2) | set conceallevel=0
autocmd BufNewFile,BufRead cgdbrc setlocal syntax=vim
" Bash Style Guide: http://lug.fh-swf.de/vim/vim-bash/StyleGuideShell.en.pdf
autocmd Filetype sh :call SetIndentation(2) | let textwidth=88
autocmd FileType snippets :call SetIndentation(3)
autocmd FileType text set textwidth=100
autocmd Filetype vim :call SetIndentation(4)
autocmd Filetype xml :call SetIndentation(2)
autocmd Filetype protobuf :call SetIndentation(2)
autocmd Filetype dockerfile :call SetIndentation(4)

" syntax mappings
autocmd BufRead,BufNewFile *.proto set filetype=protobuf
autocmd BufRead,BufNewFile *.conf set filetype=json
autocmd BufRead,BufNewFile *Build.props set filetype=xml
autocmd BufRead,BufNewFile *Build.targets set filetype=xml
autocmd Filetype dockerfile set tabstop=4 | set shiftwidth=4 | set expandtab

" Force cursor to be correct.  Vim only changes the cursor in response to mode
" changes; the initial cursor is otherwise simply the active cursor in the
" terminal when vim was launched)
autocmd VimEnter * :normal :startinsert : stopinsert

" key mappings
vmap <c-o> :only
" Enter inserts new line in normal mode
nnoremap <Enter> o<Esc>
" select word with <c-space>
if !has("gui_running")
    " Konsole interprets <c-space> as <c-@> for some reason
    nnoremap <c-@> viw
else
    nnoremap <c-space> viw
endif
" toggle search highlight (the tricky part is automatically re-enabling it on
" new searches)
let hlstate = 0
nnoremap <leader><c-h> :if (hlstate%2 == 0) \| nohlsearch \| else \| set hlsearch \| endif \| let hlstate=hlstate+1<cr>
" Buffer/window management
nnoremap <s-tab> :bp<cr>
nnoremap <F5> <c-w>_<c-w><Bar>
nnoremap <leader>b :buffers<cr>:buffer<space>
nnoremap <c-s-j> :tabnext<cr>
nnoremap <c-s-k> :tabprevious<cr>
nnoremap <leader><c-a> a<cr><Up><End>
nnoremap <leader><c-s-a> a<cr><Up><End><cr>
nnoremap <leader><s-k> <s-k>
nnoremap <s-k> k<s-j>
nnoremap <c-s-/> <s-k>
" Delete/Change after cursor in (),{},[] groups (technically, it forward
" searches for a closing parenthesis, and deletes everything in its path)
nnoremap da) v])hx
nnoremap da( v])hx
nnoremap ca) v])hc
nnoremap ca( v])hc

nnoremap da} v]}hx
nnoremap da{ v]}hx
nnoremap ca} v]}hc
nnoremap ca{ v]}hc

nnoremap da] v]]hx
nnoremap da[ v]]hx
nnoremap ca] v]]hc
nnoremap ca[ v]]hc

nnoremap da' vf'hx
nnoremap dA' vF'lx
nnoremap ca' vf'hc
nnoremap cA' vF'lc

nnoremap da" vf"hx
nnoremap dA" vF"lx
nnoremap ca" vf"hc
nnoremap cA" vF"lc

nnoremap da> vf>hx
nnoremap da< vF<lx
nnoremap ca> vf>hc
nnoremap ca< vF<lc

" Make resizing windows a little easier
" nnoremap <c-w>, <c-w><lt>
" nnoremap <c-w>. <c-w>>
" nnoremap <c-w>> <c-w>5>
" nnoremap <c-w><lt> <c-w>5<lt>
nnoremap <c-q> q:
" Insert mode navigation
inoremap <c-h> <Left>
inoremap <c-b> <c-Left>
inoremap <c-j> <Down>
inoremap <c-k> <Up>
inoremap <c-l> <Right>
inoremap <c-w> <c-Right>
" Insert mode editing
" inoremap <c-n> <Del>
" inoremap <c-p> <BS>
inoremap <expr> <c-n> pumvisible() ? "\<Down>" : "\<Del>"
inoremap <expr> <c-p> pumvisible() ? "\<Up>" : "\<BS>"
"Remove all trailing whitespace by pressing F5
nnoremap <F5> :let _s=@/<Bar>:%s/\s\+$//e<Bar>:let @/=_s<Bar><CR>


" Commands

function! IsWSL()
  if has("unix")
    let lines = readfile("/proc/version")
    if lines[0] =~ "Microsoft"
      return 1
    endif
  endif
  return 0
endfunction

" see https://vim.fandom.com/wiki/Diff_current_buffer_and_the_original_file
function! s:DiffWithSaved()
    let filetype=&ft
    diffthis
    vnew | r # | normal! 1Gdd
    diffthis
    exe "setlocal bt=nofile bh=wipe nobl noswf ro ft=" . filetype
endfunction
command! DiffSaved call s:DiffWithSaved()


if IsWSL() == 1
    let s:clip = '/mnt/c/Windows/System32/clip.exe'
    if executable(s:clip)
        augroup WSLYank
            autocmd!
            autocmd TextYankPost * call system('echo '.shellescape(join(v:event.regcontents, "\<CR>")).' | '.s:clip)
        augroup END
    end
endif

" fix common typos (sweet)
:iabbrev adn and
:iabbrev frmo from
:iabbrev howevr however
:iabbrev hwo how
:iabbrev knwo know
:iabbrev siad said
:iabbrev tehn then
:iabbrev waht what
:iabbrev wihch which
:iabbrev woudl would

" Plugins
call plug#begin()
Plug 'tpope/vim-sensible'
" On-demand loading
Plug 'scrooloose/nerdtree', { 'on': 'NERDTreeToggle' }
nnoremap <leader><c-e> :NERDTreeToggle<cr>
Plug 'preservim/nerdcommenter'
let g:NERDSpaceDelims = 1
let g:NERDTrimTrailingWhitespace = 1
let g:NERDCustomDelimiters = {
    \ 'python': { 'left': '#', 'right': '' }
    \ }
Plug 'PhilRunninger/nerdtree-visual-selection'
Plug 'vim-scripts/dbext.vim'
Plug 'itchyny/lightline.vim'
Plug 'gisodal/vimgdb'
Plug 'mitchpaulus/autocorrect.vim'
Plug 'pmalek/toogle-maximize.vim'
Plug 'webdevel/tabulous'

" File search utilities (fuzzy matching)
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }

Plug 'dag/vim-fish'
Plug 'mhinz/vim-startify'
Plug 'xolox/vim-misc'
Plug 'xolox/vim-notes'
Plug 'xolox/vim-session'
let g:session_autosave = 'no'
Plug 'tpope/vim-surround'

" Git utilities
Plug 'tpope/vim-fugitive'

if !exists('g:vscode')
    Plug 'honza/vim-snippets'
    if has('python3')
        Plug 'sirver/ultisnips'
        let g:UltiSnipsSnippetDirectories=["UltiSnips", "vim-snippets"]
        " The default <c-tab> works in gvim, but not in the terminal
        let g:UltiSnipsListSnippets='<c-s-l>'
        let g:UltiSnipsJumpForwardTrigger='<tab>'
        let g:UltiSnipsJumpBackwardTrigger='<s-tab>'
    endif
endif

" python auto-completion
Plug 'davidhalter/jedi-vim'
nnoremap <F2> :call jedi#rename()<cr>
Plug 'vimjas/vim-python-pep8-indent'

" json syntax highlighting
Plug 'elzr/vim-json'

" colorschemes
Plug 'arzg/vim-colors-xcode'
Plug 'tomasr/molokai'
Plug 'el-iot/buffer-tree-explorer'

Plug 'tomtom/vimtags_vim'
" vimtags_vim depends on this
Plug 'tomtom/tlib_vim'

" Conque-GDB doesn't work with python>3.3
" Plug 'vim-scripts/Conque-GDB'

" Dictionary
" below only works for mac
" Plug 'itchyny/dictionary.vim'
Plug 'farconics/victionary'

" Grammatical and sophisticated editing support (for normal writing)
Plug 'reedes/vim-wordy'

" vimdiff for directories
Plug 'will133/vim-dirdiff'

Plug 'vimwiki/vimwiki'
" let g:vimwiki_list = [{ 'path': '~/Documents/vimwiki/', 'name': 'main_wiki', 'auto_export': 0, 'auto_toc': 0, 'template_path': '~/Documents/vimwiki/templates/' }]
let g:vimwiki_list = [{
\    'path': '~/Documents/vimwiki/',
\    'name': 'main_wiki',
\    'auto_export': 1,
\    'auto_toc': 1,
\    'template_path': '~/Documents/vimwiki/templates/'}]

" Utilities for table-style formatting
Plug 'dhruvasagar/vim-table-mode'

call plug#end()

colorscheme xcodedark
