syntax on

set autoindent
set background=dark
set backspace=indent,eol,start
set belloff=all
set expandtab
set hlsearch
set number
set omnifunc=syntaxcomplete#Complete
set shiftwidth=3
set splitright
set tabstop=3
set ttimeoutlen=100
set visualbell
" Set character code emitted for visualbell to null
set t_vb=
" searches are case insensitive unless upper case char in search text
" for some reason, need to set ignorecase before smartcase for it to work
set ignorecase
set smartcase
set cursorline

let g:default_code_text_width = 78
let g:python_highlight_all = 1
let g:termdebug_popup = 0
let g:termdebug_wide = 163

filetype plugin on

if &shell =~# 'fish$'
    set shell=bash
endif
if &term =~ '^xterm' || &term =~'^screen'
    " Normal Mode: solid block
    let &t_EI .= "\<Esc>[2 q"
    " Replace Mode: blinking block
    let &t_SR .= "\<Esc>[1 q"
    " Insert Mode: blinking vertical bar
    let &t_SI .= "\<Esc>[5 q"
endif

function SetIndentation(size, expand_tab = v:true)
    let &l:tabstop=a:size
    let &l:shiftwidth=a:size
    " let &l:expandtab=!a:expand_tab
    let &l:expandtab=a:expand_tab
endfunction

autocmd Filetype cs :call SetIndentation(3)
autocmd Filetype cpp :call SetIndentation(3) nnoremap <buffer> <C-k> :call CommentCpp()<Cr>
autocmd Filetype h :call SetIndentation(3)
autocmd Filetype py :call SetIndentation(4)
autocmd Filetype python :call SetIndentation(4)
autocmd Filetype json :call SetIndentation(2)
autocmd BufNewFile,BufRead cgdbrc setlocal syntax=vim
" Bash Style Guide: http://lug.fh-swf.de/vim/vim-bash/StyleGuideShell.en.pdf
autocmd Filetype sh :call SetIndentation(2) | let textwidth=88
autocmd FileType snippets :call SetIndentation(3)
autocmd Filetype vim :call SetIndentation(4)
autocmd Filetype xml :call SetIndentation(2)
autocmd Filetype protobuf :call SetIndentation(2)

" syntax mappings
autocmd BufRead,BufNewFile *.proto set filetype=protobuf
autocmd BufRead,BufNewFile *.conf set filetype=protobuf
autocmd BufRead,BufNewFile *Build.props set filetype=xml
autocmd BufRead,BufNewFile *Build.targets set filetype=xml

" Force cursor to be correct.  Vim only changes the cursor in response to mode
" changes; the initial cursor is otherwise simply the active cursor in the
" terminal when vim was launched)
autocmd VimEnter * :normal :startinsert : stopinsert

" key mappings
vmap <c-o> :only
" Enter inserts new line in normal mode
nnoremap <Enter> o<Esc>
" select word with <c-space>
if !has("gui_running")
    " Konsole interprets <c-space> as <c-@> for some reason
    nnoremap <c-@> viw
else
    nnoremap <c-space> viw
endif
" toggle search highlight (the tricky part is automatically re-enabling it on
" new searches)
let hlstate = 0
nnoremap <leader><c-h> :if (hlstate%2 == 0) \| nohlsearch \| else \| set hlsearch \| endif \| let hlstate=hlstate+1<cr>
" Buffer/window management
nnoremap <s-tab> :bp<cr>
nnoremap <F5> <c-w>_<c-w><Bar>
nnoremap <leader>b :buffers<cr>:buffer<space>
nnoremap <c-s-j> :tabnext<cr>
nnoremap <c-s-k> :tabprevious<cr>
nnoremap <leader><c-a> a<cr><Up><End>
nnoremap <leader><c-s-a> a<cr><Up><End><cr>
nnoremap <s-k> 0i<Bs><Esc>
nnoremap <c-s-/> <s-k>
" Delete/Change after cursor in (),{},[] groups (technically, it forward
" searches for a closing parenthesis, and deletes everything in its path)
nnoremap da) v])hx
nnoremap da( v])hx
nnoremap ca) v])hc
nnoremap ca( v])hc

nnoremap da} d]}hx
nnoremap da{ v]}hx
nnoremap ca} v]}hc
nnoremap ca{ v]}hc

nnoremap da] v]]hx
nnoremap da[ v]]hx
nnoremap ca] v]]hc
nnoremap ca[ v]]hc

nnoremap da} d]\"hx
nnoremap da{ v]\"hx
nnoremap ca} v]\"hc
nnoremap ca{ v]\"hc

nnoremap da} d]>hx
nnoremap da{ v]>hx
nnoremap ca} v]>hc
nnoremap ca{ v]>hc
" Make resizing windows a little easier
" nnoremap <c-w>, <c-w><lt>
" nnoremap <c-w>. <c-w>>
" nnoremap <c-w>> <c-w>5>
" nnoremap <c-w><lt> <c-w>5<lt>
nnoremap <c-q> q:
" Insert mode navigation
inoremap <c-h> <Left>
inoremap <c-b> <c-Left>
inoremap <c-j> <Down>
inoremap <c-k> <Up>
inoremap <c-l> <Right>
inoremap <c-w> <c-Right>
" Insert mode editing
" inoremap <c-n> <Del>
" inoremap <c-p> <BS>
inoremap <expr> <c-n> pumvisible() ? "\<Down>" : "\<Del>"
inoremap <expr> <c-p> pumvisible() ? "\<Up>" : "\<BS>"

" Commands
" see https://vim.fandom.com/wiki/Diff_current_buffer_and_the_original_file
function! s:DiffWithSaved()
    let filetype=&ft
    diffthis
    vnew | r # | normal! 1Gdd
    diffthis
    exe "setlocal bt=nofile bh=wipe nobl noswf ro ft=" . filetype
endfunction
command! DiffSaved call s:DiffWithSaved()

" fix common typos (sweet)
:iabbrev adn and
:iabbrev frmo from
:iabbrev howevr however
:iabbrev hwo how
:iabbrev knwo know
:iabbrev siad said
:iabbrev tehn then
:iabbrev waht what
:iabbrev wihch which
:iabbrev woudl would

" Plugins
call plug#begin()
Plug 'tpope/vim-sensible'
" On-demand loading
Plug 'scrooloose/nerdtree', { 'on': 'NERDTreeToggle' }
nnoremap <leader><c-e> :NERDTreeToggle<cr>
Plug 'preservim/nerdcommenter'
let g:NERDSpaceDelims = 1
let g:NERDTrimTrailingWhitespace = 1
let g:NERDCustomDelimiters = {
    \ 'python': { 'left': '#', 'right': '' }
    \ }
Plug 'PhilRunninger/nerdtree-visual-selection'
Plug 'vim-scripts/dbext.vim'
Plug 'itchyny/lightline.vim'
Plug 'gisodal/vimgdb'
Plug 'mitchpaulus/autocorrect.vim'
Plug 'pmalek/toogle-maximize.vim'
Plug 'webdevel/tabulous'
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'dag/vim-fish'
Plug 'mhinz/vim-startify'
Plug 'xolox/vim-misc'
Plug 'xolox/vim-notes'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-fugitive'
if !exists('g:vscode')
    Plug 'sirver/ultisnips'
    Plug 'honza/vim-snippets'
    let g:UltiSnipsSnippetDirectories=["UltiSnips", "vim-snippets"]
    " The default <c-tab> works in gvim, but not in the terminal
    let g:UltiSnipsListSnippets='<c-s-l>'
    let g:UltiSnipsJumpForwardTrigger='<tab>'
    let g:UltiSnipsJumpBackwardTrigger='<s-tab>'
endif
Plug 'davidhalter/jedi-vim'
nnoremap <F2> :call jedi#rename()<cr>
Plug 'vimjas/vim-python-pep8-indent'
" colorschemes
Plug 'arzg/vim-colors-xcode'
Plug 'tomasr/molokai'
" Conque-GDB doesn't work with python>3.3
" Plug 'vim-scripts/Conque-GDB'
call plug#end()

colorscheme xcodedark
